### ISSUE TITLE
Some exercise fields have non-unique IDs

### ISSUE THREAD

**Issue by mtthwhggns** [apluslms/a-plus#593]
Within the same page, many labels can have the same ID. This makes it impossible to link labels with them reliably, and breaks the HTML validation. 

Related: https://apluslms.github.io/accessibility-audit/patterns/fixable-a/form-controls/

**Comment by raphendyr** [comment]
MOOC-Jutut should handle this as it prefixes ids with a random string. In addition, I'm currently working to upgrade file submission forms in MOOC-Grader and I implemented same randomization there.

**Comment by Mankro** [comment]
At least the file upload input elements still have this problem. Many exercises in the same chapter page may use the same ID attributes in the HTML form.

PR https://github.com/apluslms/mooc-grader/pull/78 added random components to the questionnaire question fields so that they don't use the same id attributes in many exercises.

**Comment by Mankro** [comment]
Text input IDs were part of this issue: https://github.com/apluslms/a-plus/issues/592
PR https://github.com/apluslms/mooc-grader/pull/78 fixed them.

**Comment by Mankro** [comment]
This has already been fixed in the previously linked issues. File upload input elements were fixed in https://github.com/apluslms/mooc-grader/issues/111.
